### ISSUE TITLE
关于翻译流程的建议

### ISSUE THREAD

**Issue by hymRedemption** [Mr-Wiredancer/getting-started-with-redux#11]
我觉得咱们翻译流程换成下面的是否好一点：
1. 认领任务
2. 完成英文时间轴的打点
3. 完成中文翻译（不打点）
4. 提交PR
5. 中文翻译完成校对后，中文打点，并提交PR
6. 完成 merge

我觉得将中文翻译和中文打点分开来做有一下原因
1. 按照正常的翻译流程，翻译者应该就是这样做的。
2. 将中文翻译和打点分开可以防止，译者直接用英文打点后的文件来进行翻译（虽然不太可能有这样的）
   2.1 用打点后的文件来进行翻译的问题主要是在于分裂的翻译文章
3. 方便校对
   3.1 校对的时候其实也是翻译的过程，如果校对的时候直接对打点后的中文文件进行校对，校对的时候也容易忽略句子之间的关系和句子的整体性。因为打点文件已经明显的将句子割裂成几个部分了。翻译出来的可能就不是那么中文化了。（这个是主要原因）

**Comment by Mr-Wiredancer** [comment]
之前的做法其实主要基于我自己一个人干完全部的流程，根据中文打点会比英文烦一些，所以现在多人的确不是十分合适。

我倒是觉得，可能我们进一步把翻译和打点分开。包括英文的打点其实也不是必须的。另外一个需要考虑的是现有的 transcript 其实有些地方是错的。所以我建议每一集的字幕应该分这几个步骤:
1. 校对英文字幕，需要听视频来更正 src/ 中 transcript 的错误
2. 将英文的 transcript 翻译成中文
3. 根据中文打点，保存为 .srt 文件

每一个步骤都单独出来，独立走校对 PR 的流程。等于我们有三类 issues：校正、翻译、打点

@hymRedemption

**Comment by Mr-Wiredancer** [comment]
另外一个就是认领任务的方式，我觉得更好的是有项目管理者来创建 issues. 比如一开始全部都是校正 issues. 个别校正完成后可以发布对应的翻译 issues。以此类推。

而参与者应该在 issues 下面留言，然后管理者再将其标记为已认领酱紫。

**Comment by hymRedemption** [comment]
这样也可以  @Mr-Wiredancer

**Comment by Mr-Wiredancer** [comment]
@hymRedemption 不过我是担心流程太复杂会不会影响大家的积极性。毕竟现阶段我们还是以尽快完成为主。这个你有没有想法？

**Comment by hymRedemption** [comment]
@Mr-Wiredancer 其实觉得重在翻译吧，现在这些人专门翻译。  对于打点问题，其实可以找其他志愿者。这样就不会太复杂了。  对于每个人来说任务都比较单一。    打点相对于翻译来说没有那么高的要求吧。  你觉得如何

**Comment by hymRedemption** [comment]
@Mr-Wiredancer 流程感觉反正还是有分开的必要。   毕竟不同的阶段重点还是不一样。   翻译阶段主要考虑翻译是否够好。    打点主要就是需要对照视频看看与音频的对齐情况，还有就是是否美观。  
现阶段主要大家领任务后留的时间还是相对比较少的。真的各方面都兼顾非常好，还是不容易的。

**Comment by Mr-Wiredancer** [comment]
@hymRedemption 那我觉得就从完成大家手头的任务之后开始使用新的流程吧，没异议就可以 close 了
